<?php

namespace App\Request;

use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Type;

class CalculateProductPriceRequest extends BaseRequest
{
    #[Type('integer')]
    #[NotBlank]
    protected int $product;

    #[Type('string')]
    #[NotBlank]
    protected string $taxNumber;

    #[Type('string')]
    #[NotBlank]
    protected string $couponCode;

    public function validate(): ?array
    {
        $taxNumberRegex = "/^(DE|IT|GR|FR[A-Z]{2})[0-9]{9}$/";
        $messages = ['message' => 'validation_failed', 'errors' => []];

        if (!preg_match($taxNumberRegex, $this->taxNumber)) {
            $messages['errors'][] = [
                'property' => 'taxNumber',
                'value' => $this->taxNumber,
                'message' => 'Incorrect tax number format !',
            ];
            return $messages;
        }
        return parent::validate(); // TODO: Change the autogenerated stub
    }
}